import React from 'react';

export const COLORS = {
  bgWine: '#31122B',
  bgWineDark: '#1A0916',
  bgWineLight: '#4B1D3F',
  borderGold: '#D7AB6A',
  borderGoldLight: '#E5D4B8',
  borderWine: '#4A2040',
  goldAccent: '#D7AB6A',
  goldDark: '#9C7B4E',
  goldHover: '#E5C38E',
  cardChampagne: '#F7EFE2',
  cardWhite: '#FFFFFF',
  textDark: '#2B1022',
  textMuted: '#9C7B4E',
  textLight: '#E5D4B8',
  textWhite: '#FFFFFF',
  badgeSuccessBg: 'rgba(46, 139, 87, 0.15)',
  badgeSuccessText: '#2E8B57',
  badgeDangerBg: 'rgba(224, 80, 80, 0.15)',
  badgeDangerText: '#E05050',
  badgeWarningBg: 'rgba(215, 171, 106, 0.2)',
  badgeWarningText: '#9C7B4E',
  badgeInfoBg: 'rgba(59, 130, 246, 0.15)',
  badgeInfoText: '#2563EB',
  badgePurpleBg: 'rgba(147, 51, 234, 0.15)',
  badgePurpleText: '#7E22CE',
};

/**
 * Formats numbers into Indian Rupees (INR / ₹) with standard Indian numbering system
 */
export const formatINR = (val?: number | string) => {
  if (val === undefined || val === null || val === '') return '₹0';
  const num = Number(val);
  if (isNaN(num)) return '₹0';
  return '₹' + num.toLocaleString('en-IN');
};

export const themeStyles: Record<string, React.CSSProperties> = {
  pageContainer: {
    padding: '24px',
    maxWidth: '1380px',
    margin: '0 auto',
    width: '100%',
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '16px',
    marginBottom: '22px',
  },
  pageTitle: {
    fontSize: '24px',
    fontWeight: 800,
    color: '#FFFFFF',
    letterSpacing: '0.5px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  pageSubtitle: {
    fontSize: '13px',
    color: '#E5D4B8',
    marginTop: '4px',
    fontWeight: 500,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '16px',
    marginBottom: '24px',
  },
  panel: {
    backgroundColor: '#FFFFFF',
    border: `2px solid ${COLORS.borderGold}`,
    borderRadius: '16px',
    padding: '22px',
    color: COLORS.textDark,
    boxShadow: '0 4px 20px rgba(0,0,0,0.15)',
    marginBottom: '24px',
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '12px',
    marginBottom: '18px',
    borderBottom: `1px solid ${COLORS.borderGoldLight}`,
    paddingBottom: '12px',
  },
  panelTitle: {
    fontSize: '16px',
    fontWeight: 800,
    color: COLORS.textDark,
    letterSpacing: '0.6px',
    textTransform: 'uppercase',
  },
  colCard: {
    flex: 1,
    minWidth: '320px',
    backgroundColor: COLORS.cardChampagne,
    border: `1px solid ${COLORS.borderGold}`,
    padding: '18px',
    borderRadius: '14px',
  },
  cardTitle: {
    fontSize: '13px',
    fontWeight: 800,
    color: COLORS.textDark,
    marginBottom: '14px',
    letterSpacing: '0.8px',
    textTransform: 'uppercase',
  },
  fieldLabel: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 800,
    color: COLORS.goldDark,
    marginTop: '10px',
    marginBottom: '4px',
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
  },
  fieldInput: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    border: `1px solid ${COLORS.borderGold}`,
    borderRadius: '10px',
    padding: '10px 14px',
    fontSize: '13.5px',
    color: COLORS.textDark,
    outline: 'none',
    transition: 'border 0.2s',
  },
  fieldSelect: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    border: `1px solid ${COLORS.borderGold}`,
    borderRadius: '10px',
    padding: '10px 14px',
    fontSize: '13.5px',
    color: COLORS.textDark,
    outline: 'none',
    cursor: 'pointer',
  },
  fieldTextarea: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    border: `1px solid ${COLORS.borderGold}`,
    borderRadius: '10px',
    padding: '10px 14px',
    fontSize: '13.5px',
    color: COLORS.textDark,
    outline: 'none',
    minHeight: '80px',
    resize: 'vertical',
  },
  btnPrimary: {
    backgroundColor: COLORS.goldAccent,
    color: COLORS.textDark,
    border: 'none',
    borderRadius: '10px',
    padding: '11px 20px',
    fontSize: '13px',
    fontWeight: 800,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    transition: 'background 0.2s, transform 0.1s',
  },
  btnSecondary: {
    backgroundColor: 'transparent',
    color: COLORS.textWhite,
    border: `1px solid ${COLORS.borderGold}`,
    borderRadius: '10px',
    padding: '10px 18px',
    fontSize: '13px',
    fontWeight: 700,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
  },
  btnSmall: {
    padding: '6px 12px',
    fontSize: '11.5px',
    fontWeight: 700,
    borderRadius: '8px',
    cursor: 'pointer',
    border: 'none',
  },
  btnDelete: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#E05050',
    fontSize: '16px',
    cursor: 'pointer',
    fontWeight: 800,
    padding: '4px 8px',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '13px',
  },
  th: {
    textAlign: 'left',
    padding: '12px 14px',
    fontSize: '11px',
    fontWeight: 800,
    color: COLORS.goldDark,
    letterSpacing: '0.8px',
    textTransform: 'uppercase',
    borderBottom: `2px solid ${COLORS.borderGold}`,
    backgroundColor: 'rgba(215, 171, 106, 0.08)',
  },
  td: {
    padding: '12px 14px',
    borderBottom: `1px solid ${COLORS.borderGoldLight}`,
    color: COLORS.textDark,
    verticalAlign: 'middle',
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '4px 10px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(26, 9, 22, 0.85)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '16px',
    zIndex: 1000,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    border: `2px solid ${COLORS.borderGold}`,
    borderRadius: '18px',
    padding: '24px',
    maxWidth: '650px',
    width: '100%',
    maxHeight: '90vh',
    overflowY: 'auto',
    color: COLORS.textDark,
    boxShadow: '0 10px 35px rgba(0,0,0,0.4)',
  },
};
